services:
  app:
    build:
      context: .
    image: bookworm-nextjs-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
  db:
    image: postgres:17
    container_name: pg-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: haslo123
      POSTGRES_DB: moja_baza
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro

  
volumes:
  pgdata:
